package csvs

const (
	//世界等级减少定义
	REDUCE_WORLD_LEVEL_START = 5
	REDUCE_WORLD_LEVEL_MAX   = 1
	REDUCE_WORLD_LEVEL_TIME  = 10 //秒

	//逻辑定义
	LOGIC_TRUE  = 1
	LOGIC_FALSE = 0

	//展示队伍最大，展示卡片最大值
	SHOWTEAM_MAX = 9
	SHOWCARD_MAX = 9

	//队伍是否展示
	SHOWTEAM_HIDE   = 1
	SHOWTEAM_NOHIDE = 0

	//物品类型分类
	ITEMTYPE_NORMAL   = 1
	ITEMTYPE_ROLE     = 2
	ITEMTYPE_ICON     = 3
	ITEMTYPE_CARD     = 4
	ITEMTYPE_WEAPON   = 6
	ITEMTYPE_RELICS   = 7
	ITEMTYPE_COOKBOOK = 8
	ITEMTYPE_COOK     = 9
	ITEMTYPE_FOOD     = 10

	//人物拥有次数
	ROLE_TIMES_NORMAL_MIN = 2
	ROLE_TIMES_NORMAL_MAX = 7

	//武器背包容量，圣遗物背包容量
	WEAPON_MAX_COUNT = 2000
	RELICS_MAX_COUNT = 2000

	DROP_GUARANTEED = 10

	//五星掉落
	FIVE_STAR_TIMES_LIMIT            = 73
	FIVE_STAR_TIMES_LIMIT_EACH_VALUE = 600
	FIVE_STAT_ID1                    = 100011
	FIVE_STAT_ID2                    = 100012

	//四星掉落
	FOUR_STAR_TIMES_LIMIT            = 8
	FOUR_STAR_TIMES_LIMIT_EACH_VALUE = 5100
	FOUR_STAT_ID1                    = 10002
	FOUR_STAT_ID2                    = 100021
	FOUR_STAT_ID3                    = 100022

	//地图事件状态
	MAP_ITEM_STATE_START  = 0
	MAP_ITEM_STATE_FINISH = 9
	MAP_ITEM_STATE_END    = 10

	//事件类型，正常/奖励
	EVENT_ITEM_TYPE_NORMAL = 1
	EVENT_ITEM_TYPE_REWARD = 2

	//地图事件刷新类型
	MAP_ITEM_REFRESH_DAY  = 1
	MAP_ITEM_REFRESH_WEEK = 2
	MAP_ITEM_REFRESH_SELF = 3
	MAP_ITEM_REFRESH_JION = 4

	//地图事件刷新时间
	MAP_ITEM_REFRESH_DAY_TIME  = 10
	MAP_ITEM_REFRESH_WEEK_TIME = 20
	MAP_ITEM_REFRESH_SELF_TIME = 30

	//地图刷新类型，系统刷新/玩家刷新
	MAP_TYPE_SYSTEM = 1
	MAP_TYPE_PLAYER = 2

	//掉落总权重
	DORP_ITEM_ALL_PERCENT = 10000

	//掉落类型
	DORP_ITEM_TYPE_ITEM   = 1
	DORP_ITEM_TYPE_GROUP  = 2
	DORP_ITEM_TYPE_WEIGHT = 3

	//第四个副词条产生的概率
	OTHER_FOUR_ENTRY_YES = 2000

	//圣遗物可装备数量
	RELICS_WEAR_NUM = 5

	//武器最大精炼等级
	WEAPON_MAX_REFINE = 5

	//任务状态
	TASK_STATE_INIT   = 0
	TASK_STATE_DOING  = 1
	TASK_STATE_FINISH = 2
)
